from app.metrics.provider import MetricsSnapshotInput, MetricsSnapshotResult


class FakeMetricsProvider:
    provider_name = "fake_metrics"
    provider_version = "0.1"
    source = "fake_local"

    def collect(self, input: MetricsSnapshotInput) -> MetricsSnapshotResult:
        base = (
            input.project_id * 11
            + input.publish_intent_id * 17
            + input.publication_record_id * 37
            + len(input.target_platform) * 5
        )
        views = 100 + base
        likes = max(1, views // 10)
        comments = max(0, views // 25)
        shares = max(0, views // 40)
        favorites = max(0, views // 18)
        average_watch_time_seconds = round(8.0 + (base % 90) / 10, 1)
        completion_rate = round(0.35 + (base % 55) / 100, 2)

        return MetricsSnapshotResult(
            source=self.source,
            views=views,
            likes=likes,
            comments=comments,
            shares=shares,
            favorites=favorites,
            average_watch_time_seconds=average_watch_time_seconds,
            completion_rate=completion_rate,
            provider_payload_summary=(
                "fake/local metrics generated by FakeMetricsProvider; "
                "not real platform performance"
            ),
        )
